-- GENERATED by script/plugins/sync-migrations.js — source: plugins/hello/migrations/0001_init.sql

CREATE TABLE hello_plugin_visits (
  user_id INTEGER PRIMARY KEY REFERENCES users(id),
  count INTEGER NOT NULL DEFAULT 0
);
