-- GENERATED by script/plugins/sync-migrations.js — source: plugins/theme/migrations/0001_init.sql

CREATE TABLE theme_preferences (
  owner_id INTEGER PRIMARY KEY REFERENCES users(id),
  flavor TEXT NOT NULL DEFAULT 'default',
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
